(function () {
  "use strict";
  const { U, Store } = window.Mello;
  const statuses = ["Recebida","Em análise","Aguardando orçamento","Aguardando aprovação","Aguardando peça","Em manutenção","Em testes","Pronta","Entregue"];
  const checks = [["powersOn","Equipamento liga"],["displayWorks","Display funcionando"],["wifi","Wi‑Fi"],["usb","USB"],["printheadPresent","Cabeçote presente"],["cartridgesPresent","Cartuchos presentes"],["tankFull","Tanque cheio"],["scratches","Riscos"],["breaks","Quebras"],["oxidation","Oxidação"],["leakage","Vazamento"],["accessories","Acessórios"]];
  function orderForm(o) {
    const clients = Store.all("clients"), ck = o?.checklist || {};
    return `<form class="form-grid" id="orderForm"><input type="hidden" name="id" value="${U.esc(o?.id || "")}">
      <div class="field"><label>Cliente *</label><select name="clientId" required><option value="">Selecione</option><option value="__new__">＋ Cadastrar novo cliente nesta OS</option>${clients.map(c=>`<option value="${c.id}" ${o?.clientId===c.id?"selected":""}>${U.esc(c.name)}</option>`).join("")}</select></div>
      <div class="field"><label>Status</label><select name="status">${statuses.map(s=>`<option ${o?.status===s?"selected":""}>${s}</option>`).join("")}</select></div>
      <div class="field full" id="inlineClient" hidden><div class="card"><div class="card-head"><h2>Novo cliente</h2><span class="badge">Será salvo junto com a OS</span></div><div class="form-grid"><div class="field"><label>Nome *</label><input name="newClientName"></div><div class="field"><label>CPF</label><input name="newClientCpf"></div><div class="field"><label>Telefone</label><input name="newClientPhone"></div><div class="field"><label>WhatsApp</label><input name="newClientWhatsapp"></div><div class="field"><label>E-mail</label><input name="newClientEmail" type="email"></div><div class="field"><label>Endereço</label><input name="newClientAddress"></div><div class="field full"><label>Observações do cliente</label><textarea name="newClientNotes"></textarea></div></div></div></div>
      <div class="field"><label>Marca *</label><input name="brand" required value="${U.esc(o?.brand||"")}"></div><div class="field"><label>Modelo *</label><input name="model" required value="${U.esc(o?.model||"")}"></div>
      <div class="field"><label>Número de série</label><input name="serial" value="${U.esc(o?.serial||"")}"></div><div class="field"><label>Tipo de tinta</label><input name="inkType" value="${U.esc(o?.inkType||"")}"></div>
      <div class="field"><label>Recebido por</label><input name="receivedBy" value="${U.esc(o?.receivedBy||"")}"></div><div class="field"><label>Técnico responsável</label><input name="technician" value="${U.esc(o?.technician||"")}"></div>
      <div class="field"><label>Data e hora</label><input type="datetime-local" name="receivedAt" value="${U.esc((o?.receivedAt||U.now()).slice(0,16))}"></div><div class="field"><label>Acessórios entregues</label><input name="deliveredAccessories" value="${U.esc(o?.deliveredAccessories||"")}"></div>
      <div class="field full"><label>Defeito apresentado *</label><textarea name="reportedDefect" required>${U.esc(o?.reportedDefect||"")}</textarea></div>
      <div class="field full"><label>Checklist de entrada</label><div class="check-grid">${checks.map(([k,l])=>`<label class="check"><input type="checkbox" name="check_${k}" ${ck[k]?"checked":""}> ${l}</label>`).join("")}</div></div>
      <div class="field full"><label>Observações do checklist</label><textarea name="checklistNotes">${U.esc(ck.notes||"")}</textarea></div>
      <div class="field full"><label>Observações gerais</label><textarea name="notes">${U.esc(o?.notes||"")}</textarea></div>
      <div class="field full"><label>Serviços desta ordem</label><div id="orderServiceRows">${(o?.services||[]).map(s=>serviceRow(s)).join("")}</div><button type="button" class="btn small" data-add-order-service>＋ Adicionar serviço personalizado</button><small class="muted">O valor dos serviços atualiza automaticamente a mão de obra.</small></div>
      <div class="field full"><label>Fotos (máximo 1 MB cada)</label><input type="file" id="orderPhotos" accept="image/*" multiple><div class="photo-grid">${(o?.photos||[]).map(p=>`<img class="photo" src="${p.data}" alt="${U.esc(p.name)}">`).join("")}</div></div>
      <div class="field"><label>Mão de obra</label><input type="number" min="0" step=".01" name="laborValue" value="${o?.financial?.laborValue||0}"></div><div class="field"><label>Valor das peças</label><input type="number" min="0" step=".01" name="partsValue" value="${o?.financial?.partsValue||0}"></div>
      <div class="field"><label>Desconto</label><input type="number" min="0" step=".01" name="discount" value="${o?.financial?.discount||0}"></div><div class="field"><label>Frete</label><input type="number" min="0" step=".01" name="shipping" value="${o?.financial?.shipping||0}"></div>
      <div class="field"><label>Valor recebido</label><input type="number" min="0" step=".01" name="receivedValue" value="${o?.financial?.receivedValue||0}"></div><div class="field"><label>Forma de pagamento</label><select name="paymentMethod"><option value="">Não informado</option>${["PIX","Dinheiro","Cartão","Transferência"].map(x=>`<option ${o?.financial?.paymentMethod===x?"selected":""}>${x}</option>`).join("")}</select></div>
    </form>`;
  }
  function serviceRow(s={}){return `<div class="toolbar order-service-row"><input class="field-search service-description" placeholder="Descrição do serviço" value="${U.esc(s.description||"")}"><input class="service-value" type="number" min="0" step=".01" placeholder="Valor" value="${s.value||0}" style="width:130px"><button type="button" class="btn small danger" data-remove-service>×</button></div>`}
  function setupOrderForm(root){
    const select=root.querySelector("[name=clientId]"),inline=root.querySelector("#inlineClient"),labor=root.querySelector("[name=laborValue]");
    const toggle=()=>{inline.hidden=select.value!=="__new__";root.querySelector("[name=newClientName]").required=select.value==="__new__"};select.onchange=toggle;toggle();
    const bindRow=row=>{row.querySelector("[data-remove-service]").onclick=()=>{row.remove();sum()};row.querySelector(".service-value").oninput=sum};
    const sum=()=>{const total=[...root.querySelectorAll(".service-value")].reduce((a,x)=>a+U.num(x.value),0);if(root.querySelectorAll(".order-service-row").length)labor.value=total};
    root.querySelectorAll(".order-service-row").forEach(bindRow);
    root.querySelector("[data-add-order-service]").onclick=()=>{const wrap=document.createElement("div");wrap.innerHTML=serviceRow();const row=wrap.firstElementChild;root.querySelector("#orderServiceRows").append(row);bindRow(row);row.querySelector(".service-description").focus()};
  }
  async function saveFrom(root, old) {
    const f = root.querySelector("form"); if (!f.reportValidity()) return false;
    const d = Object.fromEntries(new FormData(f).entries()), checklist = { notes:d.checklistNotes };
    checks.forEach(([k]) => checklist[k] = !!f.elements["check_"+k].checked);
    let photos = [...(old?.photos||[])]; for (const file of [...root.querySelector("#orderPhotos").files].slice(0,5-photos.length)) photos.push({id:U.uuid(),name:file.name,data:await U.fileBase64(file),createdAt:U.now()});
    let clientId=d.clientId;
    if(clientId==="__new__"){
      if(!d.newClientName.trim())throw new Error("Informe o nome do novo cliente.");
      const client=Store.save("clients",{id:U.uuid(),name:d.newClientName.trim(),cpf:d.newClientCpf,phone:d.newClientPhone,whatsapp:d.newClientWhatsapp,email:d.newClientEmail,address:d.newClientAddress,notes:d.newClientNotes});
      Store.activity(`Cliente cadastrado pela OS: ${client.name}`,"client",client.id);clientId=client.id;
    }
    const services=[...root.querySelectorAll(".order-service-row")].map(x=>({id:U.uuid(),description:x.querySelector(".service-description").value.trim(),value:Math.max(0,U.num(x.querySelector(".service-value").value))})).filter(x=>x.description);
    const labor=services.length?services.reduce((a,x)=>a+x.value,0):U.num(d.laborValue), parts=U.num(d.partsValue), discount=U.num(d.discount), shipping=U.num(d.shipping), finalValue=Math.max(0,labor+parts+shipping-discount), received=U.num(d.receivedValue);
    const financial={laborValue:labor,partsValue:parts,discount,shipping,finalValue,receivedValue:received,paymentMethod:d.paymentMethod,paymentStatus:received<=0?"Pendente":received<finalValue?"Parcial":"Pago"};
    const status=d.status||"Recebida", timeline=[...(old?.timeline||[])];
    if(!old) timeline.push({id:U.uuid(),type:"create",title:"Ordem criada",description:"Recebimento do equipamento registrado.",createdAt:U.now()});
    else { timeline.push({id:U.uuid(),type:"edit",title:"Ordem atualizada",description:"Dados da ordem foram atualizados.",createdAt:U.now()}); if(old.status!==status) timeline.push({id:U.uuid(),type:"status",title:"Status alterado",description:`${old.status} → ${status}`,createdAt:U.now()}); if(photos.length!==old.photos?.length) timeline.push({id:U.uuid(),type:"photo",title:"Fotos adicionadas",description:`${photos.length-(old.photos?.length||0)} nova(s) foto(s).`,createdAt:U.now()}); }
    if(status==="Entregue"&&old?.status!=="Entregue") timeline.push({id:U.uuid(),type:"delivery",title:"Equipamento entregue",description:"Entrega registrada no sistema.",createdAt:U.now()});
    const item={...old,id:old?.id||U.uuid(),number:old?.number||Store.nextOrderNumber(),clientId,brand:d.brand.trim(),model:d.model.trim(),serial:d.serial.trim(),serialNormalized:U.normalize(d.serial),inkType:d.inkType,deliveredAccessories:d.deliveredAccessories,reportedDefect:d.reportedDefect,checklist,receivedBy:d.receivedBy,technician:d.technician,receivedAt:new Date(d.receivedAt).toISOString(),notes:d.notes,services,photos,status,financial,timeline};
    Store.save("orders",item); Store.activity(`${old?"OS atualizada":"Nova ordem"}: ${item.number}`,"order",item.id); Store.persist(); U.toast(`${item.number} salva com sucesso.`); window.Mello.App.route("ordens"); return true;
  }
  function edit(id){const o=id?Store.get("orders",id):null;U.modal({title:o?`Editar ${o.number}`:"Nova ordem de serviço",body:orderForm(o),wide:true,onOpen:setupOrderForm,onSave:r=>saveFrom(r,o)});}
  function detail(id){
    const o=Store.get("orders",id); if(!o)return; const c=Store.get("clients",o.clientId), history=o.serialNormalized?Store.all("orders").filter(x=>x.serialNormalized===o.serialNormalized&&x.id!==o.id):[];
    const b=Store.all("budgets").filter(x=>x.orderId===id);
    U.modal({title:`${o.number} · ${o.brand} ${o.model}`,wide:true,body:`<div class="actions" style="margin-bottom:16px"><button class="btn" data-edit-order="${o.id}">Editar</button><button class="btn" data-new-budget="${o.id}">Novo orçamento</button><button class="btn" data-pdf-order="${o.id}">PDF da OS</button><button class="btn" data-pdf-delivery="${o.id}">Comprovante</button></div><div class="grid"><div class="card span-7"><div class="card-head"><h2>Resumo</h2><span class="badge ${U.statusClass(o.status)}">${o.status}</span></div><p><b>Cliente:</b> ${U.esc(c?.name||"Cliente removido")}</p><p><b>Serial:</b> ${U.esc(o.serial||"—")} · <b>Técnico:</b> ${U.esc(o.technician||"—")}</p><p><b>Defeito:</b><br>${U.esc(o.reportedDefect)}</p><p><b>Observações:</b><br>${U.esc(o.notes||"—")}</p><h3>Serviços desta ordem</h3>${o.services?.length?`<div class="table-wrap"><table><thead><tr><th>Serviço</th><th>Valor</th></tr></thead><tbody>${o.services.map(s=>`<tr><td>${U.esc(s.description)}</td><td>${U.money(s.value)}</td></tr>`).join("")}</tbody></table></div>`:'<p class="muted">Nenhum serviço informado.</p>'}<div class="photo-grid">${o.photos.map(p=>`<img class="photo" src="${p.data}">`).join("")}</div><hr><h3>Financeiro</h3><p>Valor final: <b>${U.money(o.financial.finalValue)}</b> · Recebido: <b>${U.money(o.financial.receivedValue)}</b> · <span class="badge ${U.statusClass(o.financial.paymentStatus)}">${o.financial.paymentStatus}</span></p><h3>Orçamentos</h3>${b.length?b.map(x=>`<p><b>${x.number}</b> · ${U.money(x.total)} · <span class="badge ${U.statusClass(x.status)}">${x.status}</span></p>`).join(""):'<p class="muted">Nenhum orçamento.</p>'}<h3>Histórico deste serial</h3>${history.length?history.map(x=>`<p><button class="btn small" data-open-order="${x.id}">${x.number}</button> ${U.date(x.receivedAt)} · ${U.esc(x.reportedDefect)}</p>`).join(""):'<p class="muted">Nenhum atendimento anterior localizado.</p>'}</div><div class="card span-5"><div class="card-head"><h2>Linha do tempo</h2></div><div class="timeline">${[...o.timeline].reverse().map(e=>`<div class="event"><b>${U.esc(e.title)}</b><div>${U.esc(e.description)}</div><small>${U.dateTime(e.createdAt)}</small></div>`).join("")}</div></div></div>`,onOpen:r=>{r.querySelector("[data-edit-order]").onclick=()=>edit(id);r.querySelector("[data-new-budget]").onclick=()=>window.Mello.Budgets.edit(null,id);r.querySelector("[data-pdf-order]").onclick=()=>window.Mello.PDF.order(id);r.querySelector("[data-pdf-delivery]").onclick=()=>window.Mello.PDF.delivery(id);r.querySelectorAll("[data-open-order]").forEach(x=>x.onclick=()=>detail(x.dataset.openOrder));}});
  }
  function remove(id){const o=Store.get("orders",id);U.confirm(`Excluir ${o.number} e seus orçamentos?`,()=>{Store.all("budgets").filter(b=>b.orderId===id).forEach(b=>Store.remove("budgets",b.id));Store.remove("orders",id);Store.activity(`Ordem excluída: ${o.number}`,"order",id);Store.persist();U.toast("Ordem excluída.");window.Mello.App.render();});}
  function render(){
    const st=window.Mello.App.state,q=(st.query||"").toLowerCase(),filter=st.status||"";
    const list=Store.all("orders").filter(o=>!filter||o.status===filter).filter(o=>{const c=Store.get("clients",o.clientId);return [o.number,o.brand,o.model,o.serial,o.status,o.technician,c?.name].join(" ").toLowerCase().includes(q)});
    return U.pageHead("Ordens de Serviço","Acompanhe cada equipamento do recebimento à entrega.",`<button class="btn primary" data-action="new-order">＋ Nova ordem</button>`)+`<div class="card"><div class="toolbar"><input class="field-search" data-local-search placeholder="Buscar OS, cliente ou serial…" value="${U.esc(st.query||"")}"><select data-status-filter><option value="">Todos os status</option>${statuses.map(s=>`<option ${filter===s?"selected":""}>${s}</option>`).join("")}</select><span class="badge">${list.length}</span></div>${list.length?`<div class="table-wrap"><table><thead><tr><th>OS</th><th>Cliente</th><th>Equipamento</th><th>Serial</th><th>Status</th><th>Entrada</th><th>Ações</th></tr></thead><tbody>${list.map(o=>{const c=Store.get("clients",o.clientId);return`<tr><td><b>${o.number}</b></td><td>${U.esc(c?.name||"—")}</td><td>${U.esc(o.brand)} ${U.esc(o.model)}</td><td>${U.esc(o.serial||"—")}</td><td><span class="badge ${U.statusClass(o.status)}">${o.status}</span></td><td>${U.date(o.receivedAt)}</td><td><button class="btn small" data-order-view="${o.id}">Abrir</button> <button class="btn small" data-order-edit="${o.id}">Editar</button> <button class="btn small danger" data-order-delete="${o.id}">Excluir</button></td></tr>`}).join("")}</tbody></table></div>`:U.empty("Nenhuma ordem encontrada","Abra uma nova ordem para iniciar o atendimento.")}</div>`;
  }
  window.Mello.Orders={render,edit,detail,remove,statuses};
})();
