(function () {
  "use strict";
  const { U, Store } = window.Mello;
  const statuses = ["Recebida","Em análise","Aguardando orçamento","Aguardando aprovação","Aguardando peça","Em manutenção","Em testes","Pronta","Entregue"];
  const checks = [["printheadWorks","Cabeçote funcionando"],["powersOn","Impressora ligando"],["colorFailure","Falhando cores"],["bulkContaminated","Cores do bulk contaminadas"],["displayWorks","Display funciona"],["airIntake","Entrada de ar"],["leakage","Vazamento"],["other","Outra ocorrência"]];
  function orderForm(o) {
    const clients = Store.all("clients"), ck = o?.checklist || {};
    return `<form class="form-grid compact-order-form" id="orderForm"><input type="hidden" name="id" value="${U.esc(o?.id || "")}"><div class="field full mobile-return-row"><button type="button" class="btn return-to-list" data-close>← Voltar para Ordens</button></div>
      <div class="field full client-picker"><label>Cliente *</label><div class="client-picker-actions"><input type="search" data-client-search placeholder="Digite nome, telefone, CPF ou CNPJ" autocomplete="off"><button type="button" class="btn" data-new-client>＋ Cadastrar novo cliente</button></div><input type="hidden" name="clientId" value="${U.esc(o?.clientId||"")}"><div class="client-selected" data-client-selected hidden></div><div class="client-results" data-client-results hidden></div><small class="muted" data-client-search-result>Digite pelo menos 2 caracteres para localizar um cliente.</small></div>
      <div class="field full" id="inlineClient" hidden><div class="card"><div class="card-head"><h2>Novo cliente</h2><div class="actions"><span class="badge">Será salvo junto com a OS</span><button type="button" class="btn small" data-cancel-new-client>Cancelar</button></div></div><div class="form-grid"><div class="field"><label>Nome / Razão social *</label><input name="newClientName"></div><div class="field"><label>CPF</label><input name="newClientCpf"></div><div class="field"><label>CNPJ</label><div class="input-action"><input name="newClientCnpj"><button type="button" class="btn small" data-lookup-cnpj data-prefix="newClient">Buscar</button></div></div><div class="field"><label>CEP</label><div class="input-action"><input name="newClientCep"><button type="button" class="btn small" data-lookup-cep data-prefix="newClient">Buscar</button></div></div><div class="field"><label>Telefone</label><input name="newClientPhone"></div><div class="field"><label>WhatsApp</label><input name="newClientWhatsapp"></div><div class="field"><label>E-mail</label><input name="newClientEmail" type="email"></div><div class="field"><label>Endereço</label><input name="newClientAddress"></div><div class="field full"><label>Observações do cliente</label><textarea name="newClientNotes"></textarea></div></div></div></div>
      <div class="field compact-span-2"><label>Status</label><select name="status">${statuses.map(s=>`<option ${o?.status===s?"selected":""}>${s}</option>`).join("")}</select></div><div class="field compact-span-2"><label>Data e hora</label><input type="datetime-local" name="receivedAt" value="${U.esc((o?.receivedAt||U.now()).slice(0,16))}"></div>
      <div class="field compact-span-2"><label>Marca *</label><input name="brand" required value="${U.esc(o?.brand||"")}"></div><div class="field compact-span-2"><label>Modelo *</label><input name="model" required value="${U.esc(o?.model||"")}"></div>
      <div class="field compact-span-2"><label>Número de série</label><input name="serial" value="${U.esc(o?.serial||"")}"></div><div class="field compact-span-2"><label>Tipo de tinta</label><input name="inkType" value="${U.esc(o?.inkType||"")}"></div>
      <div class="field compact-span-2"><label>Quantidade de páginas</label><input name="pageCount" inputmode="numeric" placeholder="Ex.: 25.430" value="${U.esc(o?.pageCount||"")}"></div><div class="field compact-span-2"><label>Primeira impressão</label><input name="firstPrintInfo" placeholder="Informação livre" value="${U.esc(o?.firstPrintInfo||"")}"></div>
      <div class="field full"><label>Garantia</label><input name="warrantyInfo" placeholder="Ex.: 90 dias para o serviço realizado" value="${U.esc(o?.warrantyInfo||"")}"></div>
      <div class="field compact-span-2"><label>Recebido por</label><input name="receivedBy" value="${U.esc(o?.receivedBy||"")}"></div><div class="field compact-span-2"><label>Técnico responsável</label><input name="technician" value="${U.esc(o?.technician||"")}"></div>
      <div class="field compact-span-2"><label>Prazo de entrega</label><input type="date" name="deliveryDeadline" value="${U.esc((o?.deliveryDeadline||"").slice(0,10))}"></div><div class="field compact-span-2"><label>Acessórios entregues</label><input name="deliveredAccessories" value="${U.esc(o?.deliveredAccessories||"")}"></div>
      <div class="field full"><label>Defeito apresentado *</label><textarea name="reportedDefect" required>${U.esc(o?.reportedDefect||"")}</textarea></div>
      <div class="field full"><label>Checklist de entrada</label><div class="check-grid">${checks.map(([k,l])=>`<label class="check"><input type="checkbox" name="check_${k}" ${ck[k]?"checked":""}> ${l}</label>`).join("")}</div></div>
      <div class="field full"><label>Observações do checklist</label><textarea name="checklistNotes">${U.esc(ck.notes||"")}</textarea></div>
      <div class="field full"><label>Observações gerais</label><textarea name="notes">${U.esc(o?.notes||"")}</textarea></div>
      <div class="field full"><label>Fotos (arquivos de até 15 MB)</label><input type="file" id="orderPhotos" accept="image/*" multiple><small class="muted">Fotos grandes são otimizadas automaticamente, mantendo boa qualidade.</small><div class="photo-grid">${(o?.photos||[]).map(p=>`<img class="photo" src="${p.data}" alt="${U.esc(p.name)}">`).join("")}</div></div>
    </form>`;
  }
  function serviceRow(s={}){return `<div class="toolbar order-service-row"><input class="field-search service-description" placeholder="Descrição do serviço" value="${U.esc(s.description||"")}"><input class="service-value" type="number" min="0" step=".01" placeholder="Valor" value="${s.value||0}" style="width:130px"><button type="button" class="btn small danger" data-remove-service>×</button></div>`}
  function setupOrderForm(root){
    const select=root.querySelector("[name=clientId]"),inline=root.querySelector("#inlineClient");
    const clientSearch=root.querySelector("[data-client-search]"),clientResult=root.querySelector("[data-client-search-result]"),results=root.querySelector("[data-client-results]"),selected=root.querySelector("[data-client-selected]"),clients=Store.all("clients");
    const showSelected=()=>{
      const client=clients.find(c=>c.id===select.value);
      selected.hidden=!client;
      selected.innerHTML=client?`<span><b>${U.esc(client.name)}</b>${client.phone?` · ${U.esc(client.phone)}`:""}</span><button type="button" class="btn small" data-clear-client>Trocar</button>`:"";
      selected.querySelector("[data-clear-client]")?.addEventListener("click",()=>{select.value="";selected.hidden=true;clientSearch.value="";clientSearch.hidden=false;clientSearch.focus();clientResult.textContent="Digite pelo menos 2 caracteres para localizar um cliente."});
      clientSearch.hidden=!!client;
    };
    const renderClients=query=>{
      const normalized=U.normalize(query.trim());
      if(normalized.length<2){results.hidden=true;results.innerHTML="";clientResult.textContent="Digite pelo menos 2 caracteres para localizar um cliente.";return}
      const matches=clients.filter(c=>U.normalize([c.name,c.phone,c.whatsapp,c.cpf,c.cnpj].join(" ")).includes(normalized)).slice(0,8);
      results.innerHTML=matches.map(c=>`<button type="button" class="client-result" data-client-id="${c.id}"><b>${U.esc(c.name)}</b><small>${U.esc(c.phone||c.whatsapp||c.cpf||c.cnpj||"Cliente cadastrado")}</small></button>`).join("");
      results.hidden=!matches.length;
      clientResult.textContent=matches.length?`${matches.length} cliente(s) encontrado(s). Selecione um resultado.`:"Nenhum cliente encontrado. Você pode cadastrar um novo.";
      results.querySelectorAll("[data-client-id]").forEach(button=>button.onclick=()=>{select.value=button.dataset.clientId;results.hidden=true;clientSearch.value="";showSelected()});
    };
    clientSearch.oninput=U.debounce(e=>renderClients(e.target.value),120);
    root.querySelector("[data-new-client]").onclick=()=>{select.value="__new__";inline.hidden=false;results.hidden=true;clientSearch.value="";selected.hidden=true;clientSearch.hidden=true;root.querySelector("[name=newClientName]").required=true;root.querySelector("[name=newClientName]").focus()};
    root.querySelector("[data-cancel-new-client]").onclick=()=>{select.value="";inline.hidden=true;root.querySelector("[name=newClientName]").required=false;clientSearch.hidden=false;clientSearch.focus();clientResult.textContent="Digite pelo menos 2 caracteres para localizar um cliente."};
    showSelected();window.Mello.Clients?.setupLookups(root);
  }
  async function saveFrom(root, old) {
    const f = root.querySelector("form"); if (!f.reportValidity()) return false;
    const d = Object.fromEntries(new FormData(f).entries()), checklist = { notes:d.checklistNotes };
    checks.forEach(([k]) => checklist[k] = !!f.elements["check_"+k].checked);
    let photos = [...(old?.photos||[])]; for (const file of [...root.querySelector("#orderPhotos").files].slice(0,5-photos.length)) photos.push({id:U.uuid(),name:file.name,data:await U.fileBase64(file),createdAt:U.now()});
    let clientId=d.clientId;
    if(!clientId)throw new Error("Localize e selecione um cliente ou cadastre um novo.");
    if(clientId==="__new__"){
      if(!d.newClientName.trim())throw new Error("Informe o nome do novo cliente.");
      const client=Store.save("clients",{id:U.uuid(),name:d.newClientName.trim(),cpf:d.newClientCpf,cnpj:d.newClientCnpj,cep:d.newClientCep,phone:d.newClientPhone,whatsapp:d.newClientWhatsapp,email:d.newClientEmail,address:d.newClientAddress,notes:d.newClientNotes});
      Store.activity(`Cliente cadastrado pela OS: ${client.name}`,"client",client.id);clientId=client.id;
    }
    const services=old?.services||[];
    const financial=old?.financial||{laborValue:0,partsValue:0,discount:0,shipping:0,finalValue:0,receivedValue:0,paymentMethod:"",paymentStatus:"Pendente"};
    const status=d.status||"Recebida", timeline=[...(old?.timeline||[])];
    if(!old) timeline.push({id:U.uuid(),type:"create",title:"Ordem criada",description:"Recebimento do equipamento registrado.",createdAt:U.now()});
    else { timeline.push({id:U.uuid(),type:"edit",title:"Ordem atualizada",description:"Dados da ordem foram atualizados.",createdAt:U.now()}); if(old.status!==status) timeline.push({id:U.uuid(),type:"status",title:"Status alterado",description:`${old.status} → ${status}`,createdAt:U.now()}); if(photos.length!==old.photos?.length) timeline.push({id:U.uuid(),type:"photo",title:"Fotos adicionadas",description:`${photos.length-(old.photos?.length||0)} nova(s) foto(s).`,createdAt:U.now()}); }
    if(status==="Entregue"&&old?.status!=="Entregue") timeline.push({id:U.uuid(),type:"delivery",title:"Equipamento entregue",description:"Entrega registrada no sistema.",createdAt:U.now()});
    const item={...old,id:old?.id||U.uuid(),number:old?.number||Store.nextOrderNumber(),clientId,brand:d.brand.trim(),model:d.model.trim(),serial:d.serial.trim(),serialNormalized:U.normalize(d.serial),inkType:d.inkType,pageCount:d.pageCount,firstPrintInfo:d.firstPrintInfo,warrantyInfo:d.warrantyInfo,deliveredAccessories:d.deliveredAccessories,reportedDefect:d.reportedDefect,checklist,receivedBy:d.receivedBy,technician:d.technician,receivedAt:new Date(d.receivedAt).toISOString(),deliveryDeadline:d.deliveryDeadline||"",notes:d.notes,services,photos,status,financial,timeline};
    Store.save("orders",item); Store.activity(`${old?"OS atualizada":"Nova ordem"}: ${item.number}`,"order",item.id); Store.persist(); U.toast(`${item.number} salva com sucesso.`); window.Mello.App.route("ordens"); return true;
  }
  function edit(id){const o=id?Store.get("orders",id):null;U.modal({title:o?`Editar ${o.number}`:"Nova ordem de serviço",body:orderForm(o),wide:true,onOpen:setupOrderForm,onSave:r=>saveFrom(r,o)});}
  function detail(id){
    const o=Store.get("orders",id); if(!o)return; const c=Store.get("clients",o.clientId), history=o.serialNormalized?Store.all("orders").filter(x=>x.serialNormalized===o.serialNormalized&&x.id!==o.id):[];
    const b=Store.all("budgets").filter(x=>x.orderId===id);
    U.modal({title:`${o.number} · ${o.brand} ${o.model}`,wide:true,body:`<div class="actions" style="margin-bottom:16px"><button class="btn" data-edit-order="${o.id}">Editar</button><button class="btn" data-new-budget="${o.id}">Novo orçamento</button><button class="btn" data-pdf-order="${o.id}">PDF da OS</button><button class="btn" data-pdf-delivery="${o.id}">Comprovante</button></div><div class="grid"><div class="card span-7"><div class="card-head"><h2>Resumo</h2><span class="badge ${U.statusClass(o.status)}">${o.status}</span></div><p><b>Cliente:</b> ${U.esc(c?.name||"Cliente removido")}</p><p><b>Serial:</b> ${U.esc(o.serial||"—")} · <b>Técnico:</b> ${U.esc(o.technician||"—")}</p><p><b>Defeito:</b><br>${U.esc(o.reportedDefect)}</p><p><b>Observações:</b><br>${U.esc(o.notes||"—")}</p><h3>Serviços desta ordem</h3>${o.services?.length?`<div class="table-wrap"><table><thead><tr><th>Serviço</th><th>Valor</th></tr></thead><tbody>${o.services.map(s=>`<tr><td>${U.esc(s.description)}</td><td>${U.money(s.value)}</td></tr>`).join("")}</tbody></table></div>`:'<p class="muted">Nenhum serviço informado.</p>'}<div class="photo-grid">${o.photos.map(p=>`<img class="photo" src="${p.data}">`).join("")}</div><hr><h3>Financeiro</h3><p>Valor final: <b>${U.money(o.financial.finalValue)}</b> · Recebido: <b>${U.money(o.financial.receivedValue)}</b> · <span class="badge ${U.statusClass(o.financial.paymentStatus)}">${o.financial.paymentStatus}</span></p><h3>Orçamentos</h3>${b.length?b.map(x=>`<p><b>${x.number}</b> · ${U.money(x.total)} · <span class="badge ${U.statusClass(x.status)}">${x.status}</span></p>`).join(""):'<p class="muted">Nenhum orçamento.</p>'}<h3>Histórico deste serial</h3>${history.length?history.map(x=>`<p><button class="btn small" data-open-order="${x.id}">${x.number}</button> ${U.date(x.receivedAt)} · ${U.esc(x.reportedDefect)}</p>`).join(""):'<p class="muted">Nenhum atendimento anterior localizado.</p>'}</div><div class="card span-5"><div class="card-head"><h2>Linha do tempo</h2></div><div class="timeline">${[...o.timeline].reverse().map(e=>`<div class="event"><b>${U.esc(e.title)}</b><div>${U.esc(e.description)}</div><small>${U.dateTime(e.createdAt)}</small></div>`).join("")}</div></div></div>`,onOpen:r=>{r.querySelector("[data-edit-order]").onclick=()=>edit(id);r.querySelector("[data-new-budget]").onclick=()=>window.Mello.Budgets.edit(null,id);r.querySelector("[data-pdf-order]").onclick=()=>window.Mello.PDF.order(id);r.querySelector("[data-pdf-delivery]").onclick=()=>window.Mello.PDF.delivery(id);r.querySelectorAll("[data-open-order]").forEach(x=>x.onclick=()=>detail(x.dataset.openOrder));}});
  }
  function remove(id){const o=Store.get("orders",id);U.confirm(`Excluir ${o.number} e seus orçamentos?`,()=>{Store.all("budgets").filter(b=>b.orderId===id).forEach(b=>Store.remove("budgets",b.id));Store.remove("orders",id);Store.activity(`Ordem excluída: ${o.number}`,"order",id);Store.persist();U.toast("Ordem excluída.");window.Mello.App.render();});}
  function render(){
    const st=window.Mello.App.state,q=(st.query||"").toLowerCase(),filter=st.status||"";
    const list=Store.all("orders").filter(o=>!filter||o.status===filter).filter(o=>{const c=Store.get("clients",o.clientId);return [o.number,o.brand,o.model,o.serial,o.status,o.technician,c?.name].join(" ").toLowerCase().includes(q)});
    return U.pageHead("Ordens de Serviço","Acompanhe cada equipamento do recebimento à entrega.",`<button class="btn primary" data-action="new-order">＋ Nova ordem</button>`)+`<div class="card"><div class="toolbar"><input class="field-search" data-local-search placeholder="Buscar OS, cliente ou serial…" value="${U.esc(st.query||"")}"><select data-status-filter><option value="">Todos os status</option>${statuses.map(s=>`<option ${filter===s?"selected":""}>${s}</option>`).join("")}</select><span class="badge">${list.length}</span></div>${list.length?`<div class="table-wrap"><table><thead><tr><th>OS</th><th>Cliente</th><th>Equipamento</th><th>Serial</th><th>Status</th><th>Entrada</th><th>Ações</th></tr></thead><tbody>${list.map(o=>{const c=Store.get("clients",o.clientId);return`<tr><td><b>${o.number}</b></td><td>${U.esc(c?.name||"—")}</td><td>${U.esc(o.brand)} ${U.esc(o.model)}</td><td>${U.esc(o.serial||"—")}</td><td><span class="badge ${U.statusClass(o.status)}">${o.status}</span></td><td>${U.date(o.receivedAt)}</td><td><button class="btn small" data-order-view="${o.id}">Abrir</button> <button class="btn small" data-order-edit="${o.id}">Editar</button> <button class="btn small danger" data-order-delete="${o.id}">Excluir</button></td></tr>`}).join("")}</tbody></table></div>`:U.empty("Nenhuma ordem encontrada","Abra uma nova ordem para iniciar o atendimento.")}</div>`;
  }
  window.Mello.Orders={render,edit,detail,remove,statuses};
})();
